import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header-component/header";
import Footer from "@/components/footer-component/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
